from enum import StrEnum


class Emotion(StrEnum):
    NEUTRAL = "NEUTRAL"
    HAPPY = "HAPPY"
    EXCITED = "EXCITED"
    SHY = "SHY"
    SAD = "SAD"
    ANGRY = "ANGRY"
    DISGUSTED = "DISGUSTED"
    FURIOUS = "FURIOUS"


class SceneId(StrEnum):
    SCENE_INTRO = "SCENE_INTRO"
    SCENE_FIRST_MEET = "SCENE_FIRST_MEET"
    SCENE_PROJECT_PLAN_EVALUATION = "SCENE_PROJECT_PLAN_EVALUATION"
    SCENE_LAUNCH_CEREMONY = "SCENE_LAUNCH_CEREMONY"
    SCENE_MID_EVALUATION = "SCENE_MID_EVALUATION"
    SCENE_DEEP_DEV = "SCENE_DEEP_DEV"
    SCENE_FINAL_EVALUATION = "SCENE_FINAL_EVALUATION"
    SCENE_GRADUATION_BUSAN = "SCENE_GRADUATION_BUSAN"
    SCENE_ENDING_INSTANT_BAD = "SCENE_ENDING_INSTANT_BAD"
    SCENE_ENDING_BAD = "SCENE_ENDING_BAD"
    SCENE_ENDING_NORMAL_NO_CONTACT = "SCENE_ENDING_NORMAL_NO_CONTACT"
    SCENE_ENDING_NORMAL_CONTACT = "SCENE_ENDING_NORMAL_CONTACT"
    SCENE_ENDING_HAPPY = "SCENE_ENDING_HAPPY"
    SCENE_ENDING_MARRIAGE = "SCENE_ENDING_MARRIAGE"


class EventId(StrEnum):
    EVENT_LIKE_P30 = "EVENT_LIKE_P30"
    EVENT_LIKE_P50 = "EVENT_LIKE_P50"
    EVENT_LIKE_P70 = "EVENT_LIKE_P70"
    EVENT_LIKE_P100 = "EVENT_LIKE_P100"
    EVENT_DISLIKE_M30 = "EVENT_DISLIKE_M30"
    EVENT_DISLIKE_M50 = "EVENT_DISLIKE_M50"
    EVENT_DISLIKE_M70 = "EVENT_DISLIKE_M70"


class EndingId(StrEnum):
    ENDING_INSTANT_BAD = "ENDING_INSTANT_BAD"
    ENDING_BAD = "ENDING_BAD"
    ENDING_NORMAL_NO_CONTACT = "ENDING_NORMAL_NO_CONTACT"
    ENDING_NORMAL_CONTACT = "ENDING_NORMAL_CONTACT"
    ENDING_HAPPY = "ENDING_HAPPY"
    ENDING_MARRIAGE = "ENDING_MARRIAGE"


class MessageRole(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    NARRATION = "NARRATION"
    SYSTEM_EVENT = "SYSTEM_EVENT"


ENDING_SCENE_IDS: frozenset[SceneId] = frozenset(
    {
        SceneId.SCENE_ENDING_INSTANT_BAD,
        SceneId.SCENE_ENDING_BAD,
        SceneId.SCENE_ENDING_NORMAL_NO_CONTACT,
        SceneId.SCENE_ENDING_NORMAL_CONTACT,
        SceneId.SCENE_ENDING_HAPPY,
        SceneId.SCENE_ENDING_MARRIAGE,
    }
)


SCENE_TO_ENDING: dict[SceneId, EndingId] = {
    SceneId.SCENE_ENDING_INSTANT_BAD: EndingId.ENDING_INSTANT_BAD,
    SceneId.SCENE_ENDING_BAD: EndingId.ENDING_BAD,
    SceneId.SCENE_ENDING_NORMAL_NO_CONTACT: EndingId.ENDING_NORMAL_NO_CONTACT,
    SceneId.SCENE_ENDING_NORMAL_CONTACT: EndingId.ENDING_NORMAL_CONTACT,
    SceneId.SCENE_ENDING_HAPPY: EndingId.ENDING_HAPPY,
    SceneId.SCENE_ENDING_MARRIAGE: EndingId.ENDING_MARRIAGE,
}
